### ISSUE TITLE
Package Restore doesn't restore for projects not immediately in solution dir

### ISSUE THREAD

**Issue by bc3tech** [NuGet/NuGet.VisualStudioExtension#17]
I've got a solution structured as follows:
```
Solution
  |-Project 1
  |-Project 2
```
where the projects have nuget dependencies. Nuget package restore works great.
Now, let's say `Project 1` depends on a nuget package for which I build a separate project & solution to create that package. But I want to debug in to my local code. I change my solution to be the following
```
Solution
  |-Project 1
  |-Project 2
  |-dependencies*
    |-nugetProj
```
`* solution folder`

Then re-target project 1's reference to be a project reference to `nugetProj`. This works well too. Until `nugetProj` *also* has nuget dependencies.
When I build the solution, which at this point executes a build on all shown projects, it **does not** restore the packages on which `nugetProj` depends. It appears to only detect packages on which `Project 1` and `Project 2` depend. Therefore my build fails until I go to the **actual solution** which holds `nugetProj` and build that, then come back in here to build this solution.

It's my opinion that Package Restore should detect the packages needed by *all projects contained in and being built by the solution* and execute the corresponding nuget fetch for them.

**Comment by deepakaravindr** [comment]
@bc3tech, I tried the following case in which all the projects were created on the same solution. Several packages were installed on all of the projects. And, Project1 has a project reference to nugetProj. I build the solution and package restore works fine. So, solution folder is not an issue

```
Project1.sln
    |-Project1.csproj
    |-Project2.csproj
    |-dependencies
           |-nugetProj.csproj
```

In your case though, 'nugetproj' similar to 'ClassLibrary1.csproj' above comes a different solution, right?
This can be a problem for package restore. Because, the separate solution on which you created 'nugetproj' will install packages to its 'packages' folder. And, hintpath on the csproj file to the dlls from installed NuGet packages will be relative to the separate solution created. Whereas, the solution with Project1 and Project2 will have a different packages folder and package restore is not going happen as desired

In order to overcome this, we recommend using a custom 'RepositoryPath' on which to install and restore packages. And, use the same repositorypath on both the solutions. You need to create a nuget.config file at solution level on both the solutions and configure the same repositoryPath. For more information, check out http://docs.nuget.org/consume/NuGet-Config-Settings

Please let us know if this does not answer your question

**Comment by bc3tech** [comment]
Your explanation as to the difficulty this presents makes perfect sense; it's what I expected when I wrote the issue.
Your suggestion on using repositoryPath is a new one for me. I'll have a look at it and roll it into our environment if we can. Thank you!
